### ISSUE TITLE
Error at start.

### ISSUE THREAD

**Issue by GABRYCA** [LockBlock-dev/earnapp-earnings-watcher#3]
Hi, when I try to start using the `npm start` command I'm getting this error:

```
~/earnapp-bot/earnapp-earnings-watcher$ npm start

> earnapp-earnings-watcher@2.0.0 start /home/XXXX/earnapp-bot/earnapp-earnings-watcher
> node index.js

/home/XXXX/earnapp-bot/earnapp-earnings-watcher/index.js:38
                usage: `+ ${bytesToSize(device.bw - (old[i]?.bw ?? 0))}`,
                                                            ^

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! earnapp-earnings-watcher@2.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the earnapp-earnings-watcher@2.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/XXXX/.npm/_logs/2021-11-06T12_26_29_828Z-debug.log
```

Full debug.log:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@6.14.4
3 info using node@v10.19.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle earnapp-earnings-watcher@2.0.0~prestart: earnapp-earnings-watcher@2.0.0
6 info lifecycle earnapp-earnings-watcher@2.0.0~start: earnapp-earnings-watcher@2.0.0
7 verbose lifecycle earnapp-earnings-watcher@2.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle earnapp-earnings-watcher@2.0.0~start: PATH: /usr/share/npm/node_modules/npm-lifecycle/node-gyp-bin:>9 verbose lifecycle earnapp-earnings-watcher@2.0.0~start: CWD: /home/anonymousgca/earnapp-bot/earnapp-earnings-watcher
10 silly lifecycle earnapp-earnings-watcher@2.0.0~start: Args: [ '-c', 'node index.js' ]
11 silly lifecycle earnapp-earnings-watcher@2.0.0~start: Returned: code: 1  signal: null
12 info lifecycle earnapp-earnings-watcher@2.0.0~start: Failed to exec start script
13 verbose stack Error: earnapp-earnings-watcher@2.0.0 start: `node index.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid earnapp-earnings-watcher@2.0.0
15 verbose cwd /home/anonymousgca/earnapp-bot/earnapp-earnings-watcher
16 verbose Linux 5.11.0-27-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v10.19.0
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error earnapp-earnings-watcher@2.0.0 start: `node index.js`
22 error Exit status 1
23 error Failed at the earnapp-earnings-watcher@2.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

Hope this helps finding a possible fix.
Thanks.

**Comment by LockBlock-dev** [comment]
You need at least [Node.js](https://nodejs.org/en/) version 14 to run the program.
